server:
  port: 8020

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册进Nacos
  datasource:
    #mysql
    username: root
    password: Dhj1314520
    url: jdbc:mysql://120.46.213.254:3306/mychat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid数据源
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 120.46.213.254
    port: 6379
    password: Dhj1314520
    database: 0

#rocketmq:
#  name-server: 120.46.213.254:9876
#elasticsearch:
#  url: 120.46.213.254:9200

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.erym.im.common.model
